# Wrangler Configuration for Cappato.dev Blog
# Cloudflare Pages deployment configuration

name = "cappato-blog"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# Production environment configuration
[env.production]
name = "cappato-blog"
compatibility_date = "2024-01-01"

# Development environment configuration  
[env.development]
name = "cappato-blog-dev"
compatibility_date = "2024-01-01"

# Build configuration
[build]
command = "npm run build"
cwd = "."

# Environment variables (if needed)
[vars]
NODE_ENV = "production"

# Custom domains (to be configured in Cloudflare Dashboard)
# cappato.dev will be configured as custom domain
