name: PR Size Check (Standard)

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  label-pr-size:
    name: Label PR by Size
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Label PR based on size
        uses: cbrgm/pr-size-labeler-action@v1.2.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repository: ${{ github.repository }}
          github_pr_number: ${{ github.event.number }}
          config_file_path: '.github/pull-request-size.yml'
