name: PR Size Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  check-pr-size:
    name: Verificar Tamaño del PR
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Verificar tamaño del PR
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            
            const total = pr.data.additions + pr.data.deletions;
            const changedFiles = pr.data.changed_files;
            
            console.log(`PR #${pr.data.number}: ${total} líneas, ${changedFiles} archivos`);
            
            const MAX_LINES = 300;
            const MAX_FILES = 10;
            
            if (total > MAX_LINES || changedFiles > MAX_FILES) {
              const msg = `PR demasiado grande: ${total} líneas (max: ${MAX_LINES}), ${changedFiles} archivos (max: ${MAX_FILES}). Divide en PRs más pequeños.`;
              core.setFailed(msg);
            } else {
              console.log('PR de tamaño apropiado');
            }
